-- Copyright (c) 2026, Fry Networks. MIT.
--
-- tb_stage3_core.vhd
--
-- 100/100 HARD GATE testbench for OspreyBlake2bStage3Core.
-- Reads tb/vectors/stage3_vectors_100.txt (generated by blake2b_reference.py
-- --emit-stage3-vectors 100). Each line has 10 hex u64 slots + 4 hex u64
-- expected HashOut. Drives Stage3Core, waits pipeline latency, compares.
--
-- Byte-to-slot packing convention: slots[i] = LE u64 view of message
-- bytes[8i..8i+8]. Blake2b msg-length = 52; slots 6 low4B = bytes 48..51,
-- slot 6 hi4B and slots 7..9 = 0. Expected = struct.unpack('<4Q', digest).

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;
library std;
  use std.textio.all;
library work;
  use work.PkgBlake2b.all;

entity tb_stage3_core is
end tb_stage3_core;

architecture bench of tb_stage3_core is

  constant kClkPeriod   : time    := 10 ns;
  constant kPipeLatency : integer := 100;  -- 97 core + margin

  signal Clk         : std_logic := '0';
  signal Enable      : std_logic := '0';
  signal BlockHeader : U64Array_t(9 downto 0) := (others => (others => '0'));
  signal HashOut     : U64Array_t(3 downto 0);

  signal sim_done : boolean := false;

begin

  ClkGen: process
  begin
    if sim_done then
      wait;
    end if;
    Clk <= '0';
    wait for kClkPeriod/2;
    Clk <= '1';
    wait for kClkPeriod/2;
  end process;

  dut: entity work.OspreyBlake2bStage3Core
    port map (
      Clk         => Clk,
      Enable      => Enable,
      BlockHeader => BlockHeader,
      HashOut     => HashOut
    );

  stimulus: process
    file f              : text;
    variable line_buf   : line;
    variable status_ln  : line;
    variable slv        : std_logic_vector(63 downto 0);
    variable slots      : U64Array_t(9 downto 0);
    variable expected   : U64Array_t(3 downto 0);
    variable got        : U64Array_t(3 downto 0);
    variable pass_count : integer := 0;
    variable idx        : integer := 0;
    variable match      : boolean;
    variable slv_hash   : std_logic_vector(63 downto 0);
  begin
    Enable <= '0';
    wait for 5 * kClkPeriod;
    file_open(f, "tb/vectors/stage3_vectors_100.txt", read_mode);
    Enable <= '1';

    while not endfile(f) loop
      readline(f, line_buf);

      -- Parse 10 slots
      for j in 0 to 9 loop
        hread(line_buf, slv);
        slots(j) := unsigned(slv);
      end loop;
      -- Parse 4 expected
      for j in 0 to 3 loop
        hread(line_buf, slv);
        expected(j) := unsigned(slv);
      end loop;

      -- Drive input
      BlockHeader <= slots;
      wait for kPipeLatency * kClkPeriod;

      -- Capture
      for j in 0 to 3 loop
        got(j) := HashOut(j);
      end loop;

      -- Compare
      match := (got(0) = expected(0)) and
               (got(1) = expected(1)) and
               (got(2) = expected(2)) and
               (got(3) = expected(3));

      if match then
        pass_count := pass_count + 1;
        write(status_ln, string'("PASS "));
        write(status_ln, idx);
        write(status_ln, string'(" "));
        slv_hash := std_logic_vector(got(0));
        hwrite(status_ln, slv_hash);
        writeline(output, status_ln);
      else
        write(status_ln, string'("FAIL "));
        write(status_ln, idx);
        write(status_ln, string'(" exp="));
        slv_hash := std_logic_vector(expected(0)); hwrite(status_ln, slv_hash);
        write(status_ln, string'(":"));
        slv_hash := std_logic_vector(expected(1)); hwrite(status_ln, slv_hash);
        write(status_ln, string'(":"));
        slv_hash := std_logic_vector(expected(2)); hwrite(status_ln, slv_hash);
        write(status_ln, string'(":"));
        slv_hash := std_logic_vector(expected(3)); hwrite(status_ln, slv_hash);
        write(status_ln, string'(" got="));
        slv_hash := std_logic_vector(got(0)); hwrite(status_ln, slv_hash);
        write(status_ln, string'(":"));
        slv_hash := std_logic_vector(got(1)); hwrite(status_ln, slv_hash);
        write(status_ln, string'(":"));
        slv_hash := std_logic_vector(got(2)); hwrite(status_ln, slv_hash);
        write(status_ln, string'(":"));
        slv_hash := std_logic_vector(got(3)); hwrite(status_ln, slv_hash);
        writeline(output, status_ln);
      end if;
      idx := idx + 1;
    end loop;

    file_close(f);

    write(status_ln, string'("RESULT: "));
    write(status_ln, pass_count);
    write(status_ln, string'("/"));
    write(status_ln, idx);
    write(status_ln, string'(" PASS"));
    writeline(output, status_ln);

    sim_done <= true;
    wait;
  end process;

end bench;
